---
# mkdocs.yml

site_name: notes
site_url: https://kraker.github.io/notes
repo_url: https://github.com/kraker/notes
site_author: kraker

nav:
  - index: 'index.md'
  - repo: https://github.com/kraker/notes
  - alexkraker.com: https://alexkraker.com

theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - revision.date
    - revision.history

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - tables
  - footnotes
  - meta
  - toc:
      permalink: "#"
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
