---
# mkdocs.yml

site_name: notes
site_url: https://kraker.github.io/notes/
repo_url: https://github.com/kraker/notes/
site_author: Alex Kraker
site_description: "My second brain, a collection of notes, thoughts, and ideas."
copyright: "Copyright © 2025 Alex Kraker"

nav:
  - home: 'index.md'
  - index: 'old-index.md'

theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - revision.date
    - revision.history

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - tables
  - footnotes
  - meta
  - toc:
      permalink: "#"
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
